spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_DOMAIN}
spring.security.oauth2.resourceserver.jwt.audiences=${AUTH_AUDIENCE}

gemini.api-key = ${GEMINI_API_KEY}
gemini.model = ${GEMINI_MODEL:gemini-2.5-flash}

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true